apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-dashboard
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/metrics-dashboard
    targetRevision: HEAD
    path: charts/metrics-dashboard
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
